/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "dbc_funcs.h"
#include <inttypes.h>
#include <math.h> /* uses macros NAN, INFINITY, signbit, no need for -lm */
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

/* unpack754() -- unpack a floating point number from IEEE-754 format */ 
static double unpack754(const uint64_t i, const unsigned bits, const unsigned expbits) {
	if (i == 0) return 0.0;

	const uint64_t expset = ((1uLL << expbits) - 1uLL) << (bits - expbits - 1);
	if ((i & expset) == expset) { /* NaN or +/-Infinity */
		if (i & ((1uLL << (bits - expbits - 1)) - 1uLL)) /* Non zero Mantissa means NaN */
			return NAN;
		return (i & (1uLL << (bits - 1))) ? -INFINITY : INFINITY;
	}

	/* pull the significand */
	const unsigned significandbits = bits - expbits - 1; /* - 1 for sign bit */
	double result = (i & ((1LL << significandbits) - 1)); /* mask */
	result /= (1LL << significandbits);  /* convert back to float */
	result += 1.0f;                        /* add the one back on */

	/* deal with the exponent */
	const unsigned bias = (1 << (expbits - 1)) - 1;
	long long shift = ((i >> significandbits) & ((1LL << expbits) - 1)) - bias;
	while (shift > 0) { result *= 2.0; shift--; }
	while (shift < 0) { result /= 2.0; shift++; }
	
	return ((i >> (bits - 1)) & 1) ? -result : result; /* sign it, and return */
}

static inline float    unpack754_32(uint32_t i) { return unpack754(i, 32, 8); }
static inline double   unpack754_64(uint64_t i) { return unpack754(i, 64, 11); }


/* pack754() -- pack a floating point number into IEEE-754 format */ 
static uint64_t pack754(const double f, const unsigned bits, const unsigned expbits) {
	if (f == 0.0) /* get this special case out of the way */
		return signbit(f) ? (1uLL << (bits - 1)) :  0;
	if (f != f) /* NaN, encoded as Exponent == all-bits-set, Mantissa != 0, Signbit == Do not care */
		return (1uLL << (bits - 1)) - 1uLL;
	if (f == INFINITY) /* +INFINITY encoded as Mantissa == 0, Exponent == all-bits-set */
		return ((1uLL << expbits) - 1uLL) << (bits - expbits - 1);
	if (f == -INFINITY) /* -INFINITY encoded as Mantissa == 0, Exponent == all-bits-set, Signbit == 1 */
		return (1uLL << (bits - 1)) | ((1uLL << expbits) - 1uLL) << (bits - expbits - 1);

	long long sign = 0;
	double fnorm = f;
	/* check sign and begin normalization */
	if (f < 0) { sign = 1; fnorm = -f; }

	/* get the normalized form of f and track the exponent */
	int shift = 0;
	while (fnorm >= 2.0) { fnorm /= 2.0; shift++; }
	while (fnorm < 1.0)  { fnorm *= 2.0; shift--; }
	fnorm = fnorm - 1.0;

	const unsigned significandbits = bits - expbits - 1; // -1 for sign bit

	/* calculate the binary form (non-float) of the significand data */
	const long long significand = fnorm * (( 1LL << significandbits) + 0.5f);

	/* get the biased exponent */
	const long long exp = shift + ((1LL << (expbits - 1)) - 1); // shift + bias

	/* return the final answer */
	return (sign << (bits - 1)) | (exp << (bits - expbits - 1)) | significand;
}

static inline uint32_t   pack754_32(const float  f)   { return   pack754(f, 32, 8); }
static inline uint64_t   pack754_64(const double f)   { return   pack754(f, 64, 11); }


static int pack_can_0x080_PlayerControls(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Steer: start-bit 0, length 8, endianess intel, scaling 0.008, offset -1 */
	x = ((uint8_t)(o->can_0x080_PlayerControls.Steer)) & 0xff;
	i |= x;
	/* Accel: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x080_PlayerControls.Accel)) & 0xff;
	x <<= 8; 
	i |= x;
	/* Brake: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x080_PlayerControls.Brake)) & 0xff;
	x <<= 16; 
	i |= x;
	/* Gear: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x080_PlayerControls.Gear)) & 0xff;
	x <<= 24; 
	i |= x;
	/* Clutch: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x080_PlayerControls.Clutch)) & 0xff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x080_PlayerControls_tx = 1;
	return 0;
}

static int unpack_can_0x080_PlayerControls(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Steer: start-bit 0, length 8, endianess intel, scaling 0.008, offset -1 */
	x = i & 0xff;
	o->can_0x080_PlayerControls.Steer = x;
	/* Accel: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x080_PlayerControls.Accel = x;
	/* Brake: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x080_PlayerControls.Brake = x;
	/* Gear: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x080_PlayerControls.Gear = x;
	/* Clutch: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x080_PlayerControls.Clutch = x;
	o->can_0x080_PlayerControls_rx = 1;
	o->can_0x080_PlayerControls_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x080_Steer(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x080_PlayerControls.Steer);
	rval *= 0.008;
	rval += -1;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x080_Steer(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x080_PlayerControls.Steer = 0;
	if (in > 1)
		return -1;
	in += 1;
	in *= 125;
	o->can_0x080_PlayerControls.Steer = in;
	return 0;
}

int decode_can_0x080_Accel(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x080_PlayerControls.Accel);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x080_Accel(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x080_PlayerControls.Accel = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x080_PlayerControls.Accel = in;
	return 0;
}

int decode_can_0x080_Brake(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x080_PlayerControls.Brake);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x080_Brake(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x080_PlayerControls.Brake = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x080_PlayerControls.Brake = in;
	return 0;
}

int decode_can_0x080_Gear(const can_obj_dbc_funcs_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x080_PlayerControls.Gear);
	if (rval <= 7) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x080_Gear(can_obj_dbc_funcs_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x080_PlayerControls.Gear = 0;
	if (in > 7)
		return -1;
	o->can_0x080_PlayerControls.Gear = in;
	return 0;
}

int decode_can_0x080_Clutch(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x080_PlayerControls.Clutch);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x080_Clutch(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x080_PlayerControls.Clutch = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x080_PlayerControls.Clutch = in;
	return 0;
}

int print_can_0x080_PlayerControls(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Steer = (wire: %.0f)\n", (double)(o->can_0x080_PlayerControls.Steer)));
	r = print_helper(r, fprintf(output, "Accel = (wire: %.0f)\n", (double)(o->can_0x080_PlayerControls.Accel)));
	r = print_helper(r, fprintf(output, "Brake = (wire: %.0f)\n", (double)(o->can_0x080_PlayerControls.Brake)));
	r = print_helper(r, fprintf(output, "Gear = (wire: %.0f)\n", (double)(o->can_0x080_PlayerControls.Gear)));
	r = print_helper(r, fprintf(output, "Clutch = (wire: %.0f)\n", (double)(o->can_0x080_PlayerControls.Clutch)));
	return r;
}

static int pack_can_0x300_ObstacleSensorsA(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ObstacleSensor0: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x300_ObstacleSensorsA.ObstacleSensor0)) & 0xff;
	i |= x;
	/* ObstacleSensor1: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x300_ObstacleSensorsA.ObstacleSensor1)) & 0xff;
	x <<= 8; 
	i |= x;
	/* ObstacleSensor2: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x300_ObstacleSensorsA.ObstacleSensor2)) & 0xff;
	x <<= 16; 
	i |= x;
	/* ObstacleSensor3: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x300_ObstacleSensorsA.ObstacleSensor3)) & 0xff;
	x <<= 24; 
	i |= x;
	/* ObstacleSensor4: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x300_ObstacleSensorsA.ObstacleSensor4)) & 0xff;
	x <<= 32; 
	i |= x;
	/* ObstacleSensor5: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x300_ObstacleSensorsA.ObstacleSensor5)) & 0xff;
	x <<= 40; 
	i |= x;
	/* ObstacleSensor6: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x300_ObstacleSensorsA.ObstacleSensor6)) & 0xff;
	x <<= 48; 
	i |= x;
	/* ObstacleSensor7: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x300_ObstacleSensorsA.ObstacleSensor7)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x300_ObstacleSensorsA_tx = 1;
	return 0;
}

static int unpack_can_0x300_ObstacleSensorsA(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ObstacleSensor0: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = i & 0xff;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor0 = x;
	/* ObstacleSensor1: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor1 = x;
	/* ObstacleSensor2: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor2 = x;
	/* ObstacleSensor3: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor3 = x;
	/* ObstacleSensor4: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor4 = x;
	/* ObstacleSensor5: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor5 = x;
	/* ObstacleSensor6: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor6 = x;
	/* ObstacleSensor7: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor7 = x;
	o->can_0x300_ObstacleSensorsA_rx = 1;
	o->can_0x300_ObstacleSensorsA_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x300_ObstacleSensor0(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor0);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_ObstacleSensor0(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x300_ObstacleSensorsA.ObstacleSensor0 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor0 = in;
	return 0;
}

int decode_can_0x300_ObstacleSensor1(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor1);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_ObstacleSensor1(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x300_ObstacleSensorsA.ObstacleSensor1 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor1 = in;
	return 0;
}

int decode_can_0x300_ObstacleSensor2(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor2);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_ObstacleSensor2(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x300_ObstacleSensorsA.ObstacleSensor2 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor2 = in;
	return 0;
}

int decode_can_0x300_ObstacleSensor3(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor3);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_ObstacleSensor3(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x300_ObstacleSensorsA.ObstacleSensor3 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor3 = in;
	return 0;
}

int decode_can_0x300_ObstacleSensor4(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor4);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_ObstacleSensor4(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x300_ObstacleSensorsA.ObstacleSensor4 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor4 = in;
	return 0;
}

int decode_can_0x300_ObstacleSensor5(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor5);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_ObstacleSensor5(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x300_ObstacleSensorsA.ObstacleSensor5 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor5 = in;
	return 0;
}

int decode_can_0x300_ObstacleSensor6(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor6);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_ObstacleSensor6(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x300_ObstacleSensorsA.ObstacleSensor6 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor6 = in;
	return 0;
}

int decode_can_0x300_ObstacleSensor7(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor7);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_ObstacleSensor7(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x300_ObstacleSensorsA.ObstacleSensor7 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x300_ObstacleSensorsA.ObstacleSensor7 = in;
	return 0;
}

int print_can_0x300_ObstacleSensorsA(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ObstacleSensor0 = (wire: %.0f)\n", (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor0)));
	r = print_helper(r, fprintf(output, "ObstacleSensor1 = (wire: %.0f)\n", (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor1)));
	r = print_helper(r, fprintf(output, "ObstacleSensor2 = (wire: %.0f)\n", (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor2)));
	r = print_helper(r, fprintf(output, "ObstacleSensor3 = (wire: %.0f)\n", (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor3)));
	r = print_helper(r, fprintf(output, "ObstacleSensor4 = (wire: %.0f)\n", (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor4)));
	r = print_helper(r, fprintf(output, "ObstacleSensor5 = (wire: %.0f)\n", (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor5)));
	r = print_helper(r, fprintf(output, "ObstacleSensor6 = (wire: %.0f)\n", (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor6)));
	r = print_helper(r, fprintf(output, "ObstacleSensor7 = (wire: %.0f)\n", (double)(o->can_0x300_ObstacleSensorsA.ObstacleSensor7)));
	return r;
}

static int pack_can_0x301_ObstacleSensorsB(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ObstacleSensor8: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x301_ObstacleSensorsB.ObstacleSensor8)) & 0xff;
	i |= x;
	/* ObstacleSensor9: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x301_ObstacleSensorsB.ObstacleSensor9)) & 0xff;
	x <<= 8; 
	i |= x;
	/* ObstacleSensor10: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x301_ObstacleSensorsB.ObstacleSensor10)) & 0xff;
	x <<= 16; 
	i |= x;
	/* ObstacleSensor11: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x301_ObstacleSensorsB.ObstacleSensor11)) & 0xff;
	x <<= 24; 
	i |= x;
	/* ObstacleSensor12: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x301_ObstacleSensorsB.ObstacleSensor12)) & 0xff;
	x <<= 32; 
	i |= x;
	/* ObstacleSensor13: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x301_ObstacleSensorsB.ObstacleSensor13)) & 0xff;
	x <<= 40; 
	i |= x;
	/* ObstacleSensor14: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x301_ObstacleSensorsB.ObstacleSensor14)) & 0xff;
	x <<= 48; 
	i |= x;
	/* ObstacleSensor15: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x301_ObstacleSensorsB.ObstacleSensor15)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x301_ObstacleSensorsB_tx = 1;
	return 0;
}

static int unpack_can_0x301_ObstacleSensorsB(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ObstacleSensor8: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = i & 0xff;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor8 = x;
	/* ObstacleSensor9: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor9 = x;
	/* ObstacleSensor10: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor10 = x;
	/* ObstacleSensor11: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor11 = x;
	/* ObstacleSensor12: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor12 = x;
	/* ObstacleSensor13: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor13 = x;
	/* ObstacleSensor14: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor14 = x;
	/* ObstacleSensor15: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor15 = x;
	o->can_0x301_ObstacleSensorsB_rx = 1;
	o->can_0x301_ObstacleSensorsB_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x301_ObstacleSensor8(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor8);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_ObstacleSensor8(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x301_ObstacleSensorsB.ObstacleSensor8 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor8 = in;
	return 0;
}

int decode_can_0x301_ObstacleSensor9(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor9);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_ObstacleSensor9(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x301_ObstacleSensorsB.ObstacleSensor9 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor9 = in;
	return 0;
}

int decode_can_0x301_ObstacleSensor10(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor10);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_ObstacleSensor10(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x301_ObstacleSensorsB.ObstacleSensor10 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor10 = in;
	return 0;
}

int decode_can_0x301_ObstacleSensor11(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor11);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_ObstacleSensor11(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x301_ObstacleSensorsB.ObstacleSensor11 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor11 = in;
	return 0;
}

int decode_can_0x301_ObstacleSensor12(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor12);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_ObstacleSensor12(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x301_ObstacleSensorsB.ObstacleSensor12 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor12 = in;
	return 0;
}

int decode_can_0x301_ObstacleSensor13(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor13);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_ObstacleSensor13(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x301_ObstacleSensorsB.ObstacleSensor13 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor13 = in;
	return 0;
}

int decode_can_0x301_ObstacleSensor14(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor14);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_ObstacleSensor14(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x301_ObstacleSensorsB.ObstacleSensor14 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor14 = in;
	return 0;
}

int decode_can_0x301_ObstacleSensor15(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor15);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_ObstacleSensor15(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x301_ObstacleSensorsB.ObstacleSensor15 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x301_ObstacleSensorsB.ObstacleSensor15 = in;
	return 0;
}

int print_can_0x301_ObstacleSensorsB(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ObstacleSensor8 = (wire: %.0f)\n", (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor8)));
	r = print_helper(r, fprintf(output, "ObstacleSensor9 = (wire: %.0f)\n", (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor9)));
	r = print_helper(r, fprintf(output, "ObstacleSensor10 = (wire: %.0f)\n", (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor10)));
	r = print_helper(r, fprintf(output, "ObstacleSensor11 = (wire: %.0f)\n", (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor11)));
	r = print_helper(r, fprintf(output, "ObstacleSensor12 = (wire: %.0f)\n", (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor12)));
	r = print_helper(r, fprintf(output, "ObstacleSensor13 = (wire: %.0f)\n", (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor13)));
	r = print_helper(r, fprintf(output, "ObstacleSensor14 = (wire: %.0f)\n", (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor14)));
	r = print_helper(r, fprintf(output, "ObstacleSensor15 = (wire: %.0f)\n", (double)(o->can_0x301_ObstacleSensorsB.ObstacleSensor15)));
	return r;
}

static int pack_can_0x302_ObstacleSensorsC(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ObstacleSensor16: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x302_ObstacleSensorsC.ObstacleSensor16)) & 0xff;
	i |= x;
	/* ObstacleSensor17: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x302_ObstacleSensorsC.ObstacleSensor17)) & 0xff;
	x <<= 8; 
	i |= x;
	/* ObstacleSensor18: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x302_ObstacleSensorsC.ObstacleSensor18)) & 0xff;
	x <<= 16; 
	i |= x;
	/* ObstacleSensor19: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x302_ObstacleSensorsC.ObstacleSensor19)) & 0xff;
	x <<= 24; 
	i |= x;
	/* ObstacleSensor20: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x302_ObstacleSensorsC.ObstacleSensor20)) & 0xff;
	x <<= 32; 
	i |= x;
	/* ObstacleSensor21: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x302_ObstacleSensorsC.ObstacleSensor21)) & 0xff;
	x <<= 40; 
	i |= x;
	/* ObstacleSensor22: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x302_ObstacleSensorsC.ObstacleSensor22)) & 0xff;
	x <<= 48; 
	i |= x;
	/* ObstacleSensor23: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x302_ObstacleSensorsC.ObstacleSensor23)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x302_ObstacleSensorsC_tx = 1;
	return 0;
}

static int unpack_can_0x302_ObstacleSensorsC(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ObstacleSensor16: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = i & 0xff;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor16 = x;
	/* ObstacleSensor17: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor17 = x;
	/* ObstacleSensor18: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor18 = x;
	/* ObstacleSensor19: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor19 = x;
	/* ObstacleSensor20: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor20 = x;
	/* ObstacleSensor21: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor21 = x;
	/* ObstacleSensor22: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor22 = x;
	/* ObstacleSensor23: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor23 = x;
	o->can_0x302_ObstacleSensorsC_rx = 1;
	o->can_0x302_ObstacleSensorsC_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x302_ObstacleSensor16(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor16);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x302_ObstacleSensor16(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x302_ObstacleSensorsC.ObstacleSensor16 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor16 = in;
	return 0;
}

int decode_can_0x302_ObstacleSensor17(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor17);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x302_ObstacleSensor17(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x302_ObstacleSensorsC.ObstacleSensor17 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor17 = in;
	return 0;
}

int decode_can_0x302_ObstacleSensor18(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor18);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x302_ObstacleSensor18(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x302_ObstacleSensorsC.ObstacleSensor18 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor18 = in;
	return 0;
}

int decode_can_0x302_ObstacleSensor19(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor19);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x302_ObstacleSensor19(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x302_ObstacleSensorsC.ObstacleSensor19 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor19 = in;
	return 0;
}

int decode_can_0x302_ObstacleSensor20(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor20);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x302_ObstacleSensor20(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x302_ObstacleSensorsC.ObstacleSensor20 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor20 = in;
	return 0;
}

int decode_can_0x302_ObstacleSensor21(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor21);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x302_ObstacleSensor21(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x302_ObstacleSensorsC.ObstacleSensor21 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor21 = in;
	return 0;
}

int decode_can_0x302_ObstacleSensor22(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor22);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x302_ObstacleSensor22(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x302_ObstacleSensorsC.ObstacleSensor22 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor22 = in;
	return 0;
}

int decode_can_0x302_ObstacleSensor23(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor23);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x302_ObstacleSensor23(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x302_ObstacleSensorsC.ObstacleSensor23 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x302_ObstacleSensorsC.ObstacleSensor23 = in;
	return 0;
}

int print_can_0x302_ObstacleSensorsC(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ObstacleSensor16 = (wire: %.0f)\n", (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor16)));
	r = print_helper(r, fprintf(output, "ObstacleSensor17 = (wire: %.0f)\n", (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor17)));
	r = print_helper(r, fprintf(output, "ObstacleSensor18 = (wire: %.0f)\n", (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor18)));
	r = print_helper(r, fprintf(output, "ObstacleSensor19 = (wire: %.0f)\n", (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor19)));
	r = print_helper(r, fprintf(output, "ObstacleSensor20 = (wire: %.0f)\n", (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor20)));
	r = print_helper(r, fprintf(output, "ObstacleSensor21 = (wire: %.0f)\n", (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor21)));
	r = print_helper(r, fprintf(output, "ObstacleSensor22 = (wire: %.0f)\n", (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor22)));
	r = print_helper(r, fprintf(output, "ObstacleSensor23 = (wire: %.0f)\n", (double)(o->can_0x302_ObstacleSensorsC.ObstacleSensor23)));
	return r;
}

static int pack_can_0x303_ObstacleSensorsD(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ObstacleSensor24: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x303_ObstacleSensorsD.ObstacleSensor24)) & 0xff;
	i |= x;
	/* ObstacleSensor25: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x303_ObstacleSensorsD.ObstacleSensor25)) & 0xff;
	x <<= 8; 
	i |= x;
	/* ObstacleSensor26: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x303_ObstacleSensorsD.ObstacleSensor26)) & 0xff;
	x <<= 16; 
	i |= x;
	/* ObstacleSensor27: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x303_ObstacleSensorsD.ObstacleSensor27)) & 0xff;
	x <<= 24; 
	i |= x;
	/* ObstacleSensor28: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x303_ObstacleSensorsD.ObstacleSensor28)) & 0xff;
	x <<= 32; 
	i |= x;
	/* ObstacleSensor29: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x303_ObstacleSensorsD.ObstacleSensor29)) & 0xff;
	x <<= 40; 
	i |= x;
	/* ObstacleSensor30: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x303_ObstacleSensorsD.ObstacleSensor30)) & 0xff;
	x <<= 48; 
	i |= x;
	/* ObstacleSensor31: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x303_ObstacleSensorsD.ObstacleSensor31)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x303_ObstacleSensorsD_tx = 1;
	return 0;
}

static int unpack_can_0x303_ObstacleSensorsD(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ObstacleSensor24: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = i & 0xff;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor24 = x;
	/* ObstacleSensor25: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor25 = x;
	/* ObstacleSensor26: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor26 = x;
	/* ObstacleSensor27: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor27 = x;
	/* ObstacleSensor28: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor28 = x;
	/* ObstacleSensor29: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor29 = x;
	/* ObstacleSensor30: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor30 = x;
	/* ObstacleSensor31: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor31 = x;
	o->can_0x303_ObstacleSensorsD_rx = 1;
	o->can_0x303_ObstacleSensorsD_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x303_ObstacleSensor24(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor24);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_ObstacleSensor24(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x303_ObstacleSensorsD.ObstacleSensor24 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor24 = in;
	return 0;
}

int decode_can_0x303_ObstacleSensor25(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor25);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_ObstacleSensor25(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x303_ObstacleSensorsD.ObstacleSensor25 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor25 = in;
	return 0;
}

int decode_can_0x303_ObstacleSensor26(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor26);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_ObstacleSensor26(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x303_ObstacleSensorsD.ObstacleSensor26 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor26 = in;
	return 0;
}

int decode_can_0x303_ObstacleSensor27(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor27);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_ObstacleSensor27(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x303_ObstacleSensorsD.ObstacleSensor27 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor27 = in;
	return 0;
}

int decode_can_0x303_ObstacleSensor28(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor28);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_ObstacleSensor28(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x303_ObstacleSensorsD.ObstacleSensor28 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor28 = in;
	return 0;
}

int decode_can_0x303_ObstacleSensor29(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor29);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_ObstacleSensor29(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x303_ObstacleSensorsD.ObstacleSensor29 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor29 = in;
	return 0;
}

int decode_can_0x303_ObstacleSensor30(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor30);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_ObstacleSensor30(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x303_ObstacleSensorsD.ObstacleSensor30 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor30 = in;
	return 0;
}

int decode_can_0x303_ObstacleSensor31(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor31);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_ObstacleSensor31(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x303_ObstacleSensorsD.ObstacleSensor31 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x303_ObstacleSensorsD.ObstacleSensor31 = in;
	return 0;
}

int print_can_0x303_ObstacleSensorsD(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ObstacleSensor24 = (wire: %.0f)\n", (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor24)));
	r = print_helper(r, fprintf(output, "ObstacleSensor25 = (wire: %.0f)\n", (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor25)));
	r = print_helper(r, fprintf(output, "ObstacleSensor26 = (wire: %.0f)\n", (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor26)));
	r = print_helper(r, fprintf(output, "ObstacleSensor27 = (wire: %.0f)\n", (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor27)));
	r = print_helper(r, fprintf(output, "ObstacleSensor28 = (wire: %.0f)\n", (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor28)));
	r = print_helper(r, fprintf(output, "ObstacleSensor29 = (wire: %.0f)\n", (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor29)));
	r = print_helper(r, fprintf(output, "ObstacleSensor30 = (wire: %.0f)\n", (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor30)));
	r = print_helper(r, fprintf(output, "ObstacleSensor31 = (wire: %.0f)\n", (double)(o->can_0x303_ObstacleSensorsD.ObstacleSensor31)));
	return r;
}

static int pack_can_0x304_ObstacleSensorsE(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* ObstacleSensor32: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x304_ObstacleSensorsE.ObstacleSensor32)) & 0xff;
	i |= x;
	/* ObstacleSensor33: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x304_ObstacleSensorsE.ObstacleSensor33)) & 0xff;
	x <<= 8; 
	i |= x;
	/* ObstacleSensor34: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x304_ObstacleSensorsE.ObstacleSensor34)) & 0xff;
	x <<= 16; 
	i |= x;
	/* ObstacleSensor35: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x304_ObstacleSensorsE.ObstacleSensor35)) & 0xff;
	x <<= 24; 
	i |= x;
	*data = (i);
	o->can_0x304_ObstacleSensorsE_tx = 1;
	return 0;
}

static int unpack_can_0x304_ObstacleSensorsE(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* ObstacleSensor32: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = i & 0xff;
	o->can_0x304_ObstacleSensorsE.ObstacleSensor32 = x;
	/* ObstacleSensor33: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x304_ObstacleSensorsE.ObstacleSensor33 = x;
	/* ObstacleSensor34: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x304_ObstacleSensorsE.ObstacleSensor34 = x;
	/* ObstacleSensor35: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x304_ObstacleSensorsE.ObstacleSensor35 = x;
	o->can_0x304_ObstacleSensorsE_rx = 1;
	o->can_0x304_ObstacleSensorsE_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x304_ObstacleSensor32(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x304_ObstacleSensorsE.ObstacleSensor32);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x304_ObstacleSensor32(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x304_ObstacleSensorsE.ObstacleSensor32 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x304_ObstacleSensorsE.ObstacleSensor32 = in;
	return 0;
}

int decode_can_0x304_ObstacleSensor33(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x304_ObstacleSensorsE.ObstacleSensor33);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x304_ObstacleSensor33(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x304_ObstacleSensorsE.ObstacleSensor33 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x304_ObstacleSensorsE.ObstacleSensor33 = in;
	return 0;
}

int decode_can_0x304_ObstacleSensor34(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x304_ObstacleSensorsE.ObstacleSensor34);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x304_ObstacleSensor34(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x304_ObstacleSensorsE.ObstacleSensor34 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x304_ObstacleSensorsE.ObstacleSensor34 = in;
	return 0;
}

int decode_can_0x304_ObstacleSensor35(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x304_ObstacleSensorsE.ObstacleSensor35);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x304_ObstacleSensor35(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x304_ObstacleSensorsE.ObstacleSensor35 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x304_ObstacleSensorsE.ObstacleSensor35 = in;
	return 0;
}

int print_can_0x304_ObstacleSensorsE(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "ObstacleSensor32 = (wire: %.0f)\n", (double)(o->can_0x304_ObstacleSensorsE.ObstacleSensor32)));
	r = print_helper(r, fprintf(output, "ObstacleSensor33 = (wire: %.0f)\n", (double)(o->can_0x304_ObstacleSensorsE.ObstacleSensor33)));
	r = print_helper(r, fprintf(output, "ObstacleSensor34 = (wire: %.0f)\n", (double)(o->can_0x304_ObstacleSensorsE.ObstacleSensor34)));
	r = print_helper(r, fprintf(output, "ObstacleSensor35 = (wire: %.0f)\n", (double)(o->can_0x304_ObstacleSensorsE.ObstacleSensor35)));
	return r;
}

static int pack_can_0x400_FuelGearEngine(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* FuelLevel: start-bit 0, length 29, endianess intel, scaling 1.52588e-05, offset 0 */
	x = ((uint32_t)(o->can_0x400_FuelGearEngine.FuelLevel)) & 0x1fffffff;
	i |= x;
	/* EngineSpeed: start-bit 32, length 24, endianess intel, scaling 0.00390625, offset 0 */
	x = ((uint32_t)(o->can_0x400_FuelGearEngine.EngineSpeed)) & 0xffffff;
	x <<= 32; 
	i |= x;
	/* Gear: start-bit 29, length 3, endianess intel, scaling 1, offset -1 */
	x = ((uint8_t)(o->can_0x400_FuelGearEngine.Gear)) & 0x7;
	x <<= 29; 
	i |= x;
	*data = (i);
	o->can_0x400_FuelGearEngine_tx = 1;
	return 0;
}

static int unpack_can_0x400_FuelGearEngine(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* FuelLevel: start-bit 0, length 29, endianess intel, scaling 1.52588e-05, offset 0 */
	x = i & 0x1fffffff;
	o->can_0x400_FuelGearEngine.FuelLevel = x;
	/* EngineSpeed: start-bit 32, length 24, endianess intel, scaling 0.00390625, offset 0 */
	x = (i >> 32) & 0xffffff;
	o->can_0x400_FuelGearEngine.EngineSpeed = x;
	/* Gear: start-bit 29, length 3, endianess intel, scaling 1, offset -1 */
	x = (i >> 29) & 0x7;
	o->can_0x400_FuelGearEngine.Gear = x;
	o->can_0x400_FuelGearEngine_rx = 1;
	o->can_0x400_FuelGearEngine_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x400_FuelLevel(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x400_FuelGearEngine.FuelLevel);
	rval *= 1.52588e-05;
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x400_FuelLevel(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x400_FuelGearEngine.FuelLevel = 0;
	if (in > 100)
		return -1;
	in *= 65536;
	o->can_0x400_FuelGearEngine.FuelLevel = in;
	return 0;
}

int decode_can_0x400_EngineSpeed(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x400_FuelGearEngine.EngineSpeed);
	rval *= 0.00390625;
	if (rval <= 10000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x400_EngineSpeed(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x400_FuelGearEngine.EngineSpeed = 0;
	if (in > 10000)
		return -1;
	in *= 256;
	o->can_0x400_FuelGearEngine.EngineSpeed = in;
	return 0;
}

int decode_can_0x400_Gear(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x400_FuelGearEngine.Gear);
	rval += -1;
	if (rval <= 6) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x400_Gear(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x400_FuelGearEngine.Gear = 0;
	if (in > 6)
		return -1;
	in += 1;
	o->can_0x400_FuelGearEngine.Gear = in;
	return 0;
}

int print_can_0x400_FuelGearEngine(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "FuelLevel = (wire: %.0f)\n", (double)(o->can_0x400_FuelGearEngine.FuelLevel)));
	r = print_helper(r, fprintf(output, "EngineSpeed = (wire: %.0f)\n", (double)(o->can_0x400_FuelGearEngine.EngineSpeed)));
	r = print_helper(r, fprintf(output, "Gear = (wire: %.0f)\n", (double)(o->can_0x400_FuelGearEngine.Gear)));
	return r;
}

static int pack_can_0x401_CarDamage(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Damage: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x401_CarDamage.Damage)) & 0xffffffff;
	i |= x;
	*data = (i);
	o->can_0x401_CarDamage_tx = 1;
	return 0;
}

static int unpack_can_0x401_CarDamage(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Damage: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x401_CarDamage.Damage = x;
	o->can_0x401_CarDamage_rx = 1;
	o->can_0x401_CarDamage_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x401_Damage(const can_obj_dbc_funcs_h_t *o, uint32_t *out) {
	assert(o);
	assert(out);
	uint32_t rval = (uint32_t)(o->can_0x401_CarDamage.Damage);
	*out = rval;
	return 0;
}

int encode_can_0x401_Damage(can_obj_dbc_funcs_h_t *o, uint32_t in) {
	assert(o);
	o->can_0x401_CarDamage.Damage = in;
	return 0;
}

int print_can_0x401_CarDamage(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Damage = (wire: %.0f)\n", (double)(o->can_0x401_CarDamage.Damage)));
	return r;
}

static int pack_can_0x402_WheelSpinVelocity(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* WheelSpin0: start-bit 0, length 16, endianess intel, scaling 1, offset -20000 */
	x = ((uint16_t)(o->can_0x402_WheelSpinVelocity.WheelSpin0)) & 0xffff;
	i |= x;
	/* WheelSpin1: start-bit 16, length 16, endianess intel, scaling 1, offset -20000 */
	x = ((uint16_t)(o->can_0x402_WheelSpinVelocity.WheelSpin1)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* WheelSpin2: start-bit 32, length 16, endianess intel, scaling 1, offset -20000 */
	x = ((uint16_t)(o->can_0x402_WheelSpinVelocity.WheelSpin2)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* WheelSpin3: start-bit 48, length 16, endianess intel, scaling 1, offset -20000 */
	x = ((uint16_t)(o->can_0x402_WheelSpinVelocity.WheelSpin3)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x402_WheelSpinVelocity_tx = 1;
	return 0;
}

static int unpack_can_0x402_WheelSpinVelocity(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* WheelSpin0: start-bit 0, length 16, endianess intel, scaling 1, offset -20000 */
	x = i & 0xffff;
	o->can_0x402_WheelSpinVelocity.WheelSpin0 = x;
	/* WheelSpin1: start-bit 16, length 16, endianess intel, scaling 1, offset -20000 */
	x = (i >> 16) & 0xffff;
	o->can_0x402_WheelSpinVelocity.WheelSpin1 = x;
	/* WheelSpin2: start-bit 32, length 16, endianess intel, scaling 1, offset -20000 */
	x = (i >> 32) & 0xffff;
	o->can_0x402_WheelSpinVelocity.WheelSpin2 = x;
	/* WheelSpin3: start-bit 48, length 16, endianess intel, scaling 1, offset -20000 */
	x = (i >> 48) & 0xffff;
	o->can_0x402_WheelSpinVelocity.WheelSpin3 = x;
	o->can_0x402_WheelSpinVelocity_rx = 1;
	o->can_0x402_WheelSpinVelocity_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x402_WheelSpin0(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x402_WheelSpinVelocity.WheelSpin0);
	rval += -20000;
	if (rval <= 20000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x402_WheelSpin0(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x402_WheelSpinVelocity.WheelSpin0 = 0;
	if (in > 20000)
		return -1;
	in += 20000;
	o->can_0x402_WheelSpinVelocity.WheelSpin0 = in;
	return 0;
}

int decode_can_0x402_WheelSpin1(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x402_WheelSpinVelocity.WheelSpin1);
	rval += -20000;
	if (rval <= 20000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x402_WheelSpin1(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x402_WheelSpinVelocity.WheelSpin1 = 0;
	if (in > 20000)
		return -1;
	in += 20000;
	o->can_0x402_WheelSpinVelocity.WheelSpin1 = in;
	return 0;
}

int decode_can_0x402_WheelSpin2(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x402_WheelSpinVelocity.WheelSpin2);
	rval += -20000;
	if (rval <= 20000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x402_WheelSpin2(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x402_WheelSpinVelocity.WheelSpin2 = 0;
	if (in > 20000)
		return -1;
	in += 20000;
	o->can_0x402_WheelSpinVelocity.WheelSpin2 = in;
	return 0;
}

int decode_can_0x402_WheelSpin3(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x402_WheelSpinVelocity.WheelSpin3);
	rval += -20000;
	if (rval <= 20000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x402_WheelSpin3(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x402_WheelSpinVelocity.WheelSpin3 = 0;
	if (in > 20000)
		return -1;
	in += 20000;
	o->can_0x402_WheelSpinVelocity.WheelSpin3 = in;
	return 0;
}

int print_can_0x402_WheelSpinVelocity(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "WheelSpin0 = (wire: %.0f)\n", (double)(o->can_0x402_WheelSpinVelocity.WheelSpin0)));
	r = print_helper(r, fprintf(output, "WheelSpin1 = (wire: %.0f)\n", (double)(o->can_0x402_WheelSpinVelocity.WheelSpin1)));
	r = print_helper(r, fprintf(output, "WheelSpin2 = (wire: %.0f)\n", (double)(o->can_0x402_WheelSpinVelocity.WheelSpin2)));
	r = print_helper(r, fprintf(output, "WheelSpin3 = (wire: %.0f)\n", (double)(o->can_0x402_WheelSpinVelocity.WheelSpin3)));
	return r;
}

static int pack_can_0x403_Speed(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* SpeedX: start-bit 0, length 21, endianess intel, scaling 0.001, offset -1000 */
	x = ((uint32_t)(o->can_0x403_Speed.SpeedX)) & 0x1fffff;
	i |= x;
	/* SpeedY: start-bit 21, length 21, endianess intel, scaling 0.001, offset -1000 */
	x = ((uint32_t)(o->can_0x403_Speed.SpeedY)) & 0x1fffff;
	x <<= 21; 
	i |= x;
	/* SpeedZ: start-bit 42, length 21, endianess intel, scaling 0.001, offset -1000 */
	x = ((uint32_t)(o->can_0x403_Speed.SpeedZ)) & 0x1fffff;
	x <<= 42; 
	i |= x;
	*data = (i);
	o->can_0x403_Speed_tx = 1;
	return 0;
}

static int unpack_can_0x403_Speed(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* SpeedX: start-bit 0, length 21, endianess intel, scaling 0.001, offset -1000 */
	x = i & 0x1fffff;
	o->can_0x403_Speed.SpeedX = x;
	/* SpeedY: start-bit 21, length 21, endianess intel, scaling 0.001, offset -1000 */
	x = (i >> 21) & 0x1fffff;
	o->can_0x403_Speed.SpeedY = x;
	/* SpeedZ: start-bit 42, length 21, endianess intel, scaling 0.001, offset -1000 */
	x = (i >> 42) & 0x1fffff;
	o->can_0x403_Speed.SpeedZ = x;
	o->can_0x403_Speed_rx = 1;
	o->can_0x403_Speed_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x403_SpeedX(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x403_Speed.SpeedX);
	rval *= 0.001;
	rval += -1000;
	if (rval <= 1000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x403_SpeedX(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x403_Speed.SpeedX = 0;
	if (in > 1000)
		return -1;
	in += 1000;
	in *= 1000;
	o->can_0x403_Speed.SpeedX = in;
	return 0;
}

int decode_can_0x403_SpeedY(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x403_Speed.SpeedY);
	rval *= 0.001;
	rval += -1000;
	if (rval <= 1000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x403_SpeedY(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x403_Speed.SpeedY = 0;
	if (in > 1000)
		return -1;
	in += 1000;
	in *= 1000;
	o->can_0x403_Speed.SpeedY = in;
	return 0;
}

int decode_can_0x403_SpeedZ(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x403_Speed.SpeedZ);
	rval *= 0.001;
	rval += -1000;
	if (rval <= 1000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x403_SpeedZ(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x403_Speed.SpeedZ = 0;
	if (in > 1000)
		return -1;
	in += 1000;
	in *= 1000;
	o->can_0x403_Speed.SpeedZ = in;
	return 0;
}

int print_can_0x403_Speed(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "SpeedX = (wire: %.0f)\n", (double)(o->can_0x403_Speed.SpeedX)));
	r = print_helper(r, fprintf(output, "SpeedY = (wire: %.0f)\n", (double)(o->can_0x403_Speed.SpeedY)));
	r = print_helper(r, fprintf(output, "SpeedZ = (wire: %.0f)\n", (double)(o->can_0x403_Speed.SpeedZ)));
	return r;
}

static int pack_can_0x404_Position(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Position: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x404_Position.Position)) & 0xffffffff;
	i |= x;
	/* PositionZ: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x404_Position.PositionZ) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x404_Position_tx = 1;
	return 0;
}

static int unpack_can_0x404_Position(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Position: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x404_Position.Position = x;
	/* PositionZ: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x404_Position.PositionZ = unpack754_32(x);
	o->can_0x404_Position_rx = 1;
	o->can_0x404_Position_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x404_Position(const can_obj_dbc_funcs_h_t *o, uint32_t *out) {
	assert(o);
	assert(out);
	uint32_t rval = (uint32_t)(o->can_0x404_Position.Position);
	*out = rval;
	return 0;
}

int encode_can_0x404_Position(can_obj_dbc_funcs_h_t *o, uint32_t in) {
	assert(o);
	o->can_0x404_Position.Position = in;
	return 0;
}

int decode_can_0x404_PositionZ(const can_obj_dbc_funcs_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x404_Position.PositionZ);
	if (rval <= 20000) {
		*out = rval;
		return 0;
	} else {
		*out = (float)0;
		return -1;
	}
}

int encode_can_0x404_PositionZ(can_obj_dbc_funcs_h_t *o, float in) {
	assert(o);
	o->can_0x404_Position.PositionZ = 0;
	if (in > 20000)
		return -1;
	o->can_0x404_Position.PositionZ = in;
	return 0;
}

int print_can_0x404_Position(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Position = (wire: %.0f)\n", (double)(o->can_0x404_Position.Position)));
	r = print_helper(r, fprintf(output, "PositionZ = (wire: %g)\n", (double)(o->can_0x404_Position.PositionZ)));
	return r;
}

static int pack_can_0x405_AngleAndOffset(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Angle: start-bit 0, length 16, endianess intel, scaling 0.0001, offset 0 */
	x = ((uint16_t)(o->can_0x405_AngleAndOffset.Angle)) & 0xffff;
	i |= x;
	/* DistanceFromMiddle: start-bit 16, length 16, endianess intel, scaling 5e-05, offset -1 */
	x = ((uint16_t)(o->can_0x405_AngleAndOffset.DistanceFromMiddle)) & 0xffff;
	x <<= 16; 
	i |= x;
	*data = (i);
	o->can_0x405_AngleAndOffset_tx = 1;
	return 0;
}

static int unpack_can_0x405_AngleAndOffset(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Angle: start-bit 0, length 16, endianess intel, scaling 0.0001, offset 0 */
	x = i & 0xffff;
	o->can_0x405_AngleAndOffset.Angle = x;
	/* DistanceFromMiddle: start-bit 16, length 16, endianess intel, scaling 5e-05, offset -1 */
	x = (i >> 16) & 0xffff;
	o->can_0x405_AngleAndOffset.DistanceFromMiddle = x;
	o->can_0x405_AngleAndOffset_rx = 1;
	o->can_0x405_AngleAndOffset_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x405_Angle(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x405_AngleAndOffset.Angle);
	rval *= 0.0001;
	if (rval <= 6.28319) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x405_Angle(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x405_AngleAndOffset.Angle = 0;
	if (in > 6.28319)
		return -1;
	in *= 10000;
	o->can_0x405_AngleAndOffset.Angle = in;
	return 0;
}

int decode_can_0x405_DistanceFromMiddle(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x405_AngleAndOffset.DistanceFromMiddle);
	rval *= 5e-05;
	rval += -1;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x405_DistanceFromMiddle(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x405_AngleAndOffset.DistanceFromMiddle = 0;
	if (in > 1)
		return -1;
	in += 1;
	in *= 20000;
	o->can_0x405_AngleAndOffset.DistanceFromMiddle = in;
	return 0;
}

int print_can_0x405_AngleAndOffset(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Angle = (wire: %.0f)\n", (double)(o->can_0x405_AngleAndOffset.Angle)));
	r = print_helper(r, fprintf(output, "DistanceFromMiddle = (wire: %.0f)\n", (double)(o->can_0x405_AngleAndOffset.DistanceFromMiddle)));
	return r;
}

static int pack_can_0x406_LapTime(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* CurrentLapTime: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x406_LapTime.CurrentLapTime) & 0xffffffff;
	i |= x;
	/* LastLapTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x406_LapTime.LastLapTime) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x406_LapTime_tx = 1;
	return 0;
}

static int unpack_can_0x406_LapTime(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* CurrentLapTime: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x406_LapTime.CurrentLapTime = unpack754_32(x);
	/* LastLapTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x406_LapTime.LastLapTime = unpack754_32(x);
	o->can_0x406_LapTime_rx = 1;
	o->can_0x406_LapTime_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x406_CurrentLapTime(const can_obj_dbc_funcs_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x406_LapTime.CurrentLapTime);
	if (rval <= 3600) {
		*out = rval;
		return 0;
	} else {
		*out = (float)0;
		return -1;
	}
}

int encode_can_0x406_CurrentLapTime(can_obj_dbc_funcs_h_t *o, float in) {
	assert(o);
	o->can_0x406_LapTime.CurrentLapTime = 0;
	if (in > 3600)
		return -1;
	o->can_0x406_LapTime.CurrentLapTime = in;
	return 0;
}

int decode_can_0x406_LastLapTime(const can_obj_dbc_funcs_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x406_LapTime.LastLapTime);
	if (rval <= 3600) {
		*out = rval;
		return 0;
	} else {
		*out = (float)0;
		return -1;
	}
}

int encode_can_0x406_LastLapTime(can_obj_dbc_funcs_h_t *o, float in) {
	assert(o);
	o->can_0x406_LapTime.LastLapTime = 0;
	if (in > 3600)
		return -1;
	o->can_0x406_LapTime.LastLapTime = in;
	return 0;
}

int print_can_0x406_LapTime(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "CurrentLapTime = (wire: %g)\n", (double)(o->can_0x406_LapTime.CurrentLapTime)));
	r = print_helper(r, fprintf(output, "LastLapTime = (wire: %g)\n", (double)(o->can_0x406_LapTime.LastLapTime)));
	return r;
}

static int pack_can_0x407_DistanceRaced(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* DistanceFromStartLine: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x407_DistanceRaced.DistanceFromStartLine) & 0xffffffff;
	i |= x;
	/* CurrentDistanceRaced: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x407_DistanceRaced.CurrentDistanceRaced) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x407_DistanceRaced_tx = 1;
	return 0;
}

static int unpack_can_0x407_DistanceRaced(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* DistanceFromStartLine: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x407_DistanceRaced.DistanceFromStartLine = unpack754_32(x);
	/* CurrentDistanceRaced: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x407_DistanceRaced.CurrentDistanceRaced = unpack754_32(x);
	o->can_0x407_DistanceRaced_rx = 1;
	o->can_0x407_DistanceRaced_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x407_DistanceFromStartLine(const can_obj_dbc_funcs_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x407_DistanceRaced.DistanceFromStartLine);
	if (rval <= 100000) {
		*out = rval;
		return 0;
	} else {
		*out = (float)0;
		return -1;
	}
}

int encode_can_0x407_DistanceFromStartLine(can_obj_dbc_funcs_h_t *o, float in) {
	assert(o);
	o->can_0x407_DistanceRaced.DistanceFromStartLine = 0;
	if (in > 100000)
		return -1;
	o->can_0x407_DistanceRaced.DistanceFromStartLine = in;
	return 0;
}

int decode_can_0x407_CurrentDistanceRaced(const can_obj_dbc_funcs_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x407_DistanceRaced.CurrentDistanceRaced);
	if (rval <= 100000) {
		*out = rval;
		return 0;
	} else {
		*out = (float)0;
		return -1;
	}
}

int encode_can_0x407_CurrentDistanceRaced(can_obj_dbc_funcs_h_t *o, float in) {
	assert(o);
	o->can_0x407_DistanceRaced.CurrentDistanceRaced = 0;
	if (in > 100000)
		return -1;
	o->can_0x407_DistanceRaced.CurrentDistanceRaced = in;
	return 0;
}

int print_can_0x407_DistanceRaced(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "DistanceFromStartLine = (wire: %g)\n", (double)(o->can_0x407_DistanceRaced.DistanceFromStartLine)));
	r = print_helper(r, fprintf(output, "CurrentDistanceRaced = (wire: %g)\n", (double)(o->can_0x407_DistanceRaced.CurrentDistanceRaced)));
	return r;
}

static int pack_can_0x500_TrackSensorsA(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* TrackSensor0: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x500_TrackSensorsA.TrackSensor0)) & 0xff;
	i |= x;
	/* TrackSensor1: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x500_TrackSensorsA.TrackSensor1)) & 0xff;
	x <<= 8; 
	i |= x;
	/* TrackSensor2: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x500_TrackSensorsA.TrackSensor2)) & 0xff;
	x <<= 16; 
	i |= x;
	/* TrackSensor3: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x500_TrackSensorsA.TrackSensor3)) & 0xff;
	x <<= 24; 
	i |= x;
	/* TrackSensor4: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x500_TrackSensorsA.TrackSensor4)) & 0xff;
	x <<= 32; 
	i |= x;
	/* TrackSensor5: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x500_TrackSensorsA.TrackSensor5)) & 0xff;
	x <<= 40; 
	i |= x;
	/* TrackSensor6: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x500_TrackSensorsA.TrackSensor6)) & 0xff;
	x <<= 48; 
	i |= x;
	/* TrackSensor7: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x500_TrackSensorsA.TrackSensor7)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x500_TrackSensorsA_tx = 1;
	return 0;
}

static int unpack_can_0x500_TrackSensorsA(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* TrackSensor0: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = i & 0xff;
	o->can_0x500_TrackSensorsA.TrackSensor0 = x;
	/* TrackSensor1: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x500_TrackSensorsA.TrackSensor1 = x;
	/* TrackSensor2: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x500_TrackSensorsA.TrackSensor2 = x;
	/* TrackSensor3: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x500_TrackSensorsA.TrackSensor3 = x;
	/* TrackSensor4: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x500_TrackSensorsA.TrackSensor4 = x;
	/* TrackSensor5: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x500_TrackSensorsA.TrackSensor5 = x;
	/* TrackSensor6: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x500_TrackSensorsA.TrackSensor6 = x;
	/* TrackSensor7: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x500_TrackSensorsA.TrackSensor7 = x;
	o->can_0x500_TrackSensorsA_rx = 1;
	o->can_0x500_TrackSensorsA_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x500_TrackSensor0(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x500_TrackSensorsA.TrackSensor0);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x500_TrackSensor0(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x500_TrackSensorsA.TrackSensor0 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x500_TrackSensorsA.TrackSensor0 = in;
	return 0;
}

int decode_can_0x500_TrackSensor1(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x500_TrackSensorsA.TrackSensor1);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x500_TrackSensor1(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x500_TrackSensorsA.TrackSensor1 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x500_TrackSensorsA.TrackSensor1 = in;
	return 0;
}

int decode_can_0x500_TrackSensor2(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x500_TrackSensorsA.TrackSensor2);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x500_TrackSensor2(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x500_TrackSensorsA.TrackSensor2 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x500_TrackSensorsA.TrackSensor2 = in;
	return 0;
}

int decode_can_0x500_TrackSensor3(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x500_TrackSensorsA.TrackSensor3);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x500_TrackSensor3(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x500_TrackSensorsA.TrackSensor3 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x500_TrackSensorsA.TrackSensor3 = in;
	return 0;
}

int decode_can_0x500_TrackSensor4(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x500_TrackSensorsA.TrackSensor4);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x500_TrackSensor4(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x500_TrackSensorsA.TrackSensor4 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x500_TrackSensorsA.TrackSensor4 = in;
	return 0;
}

int decode_can_0x500_TrackSensor5(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x500_TrackSensorsA.TrackSensor5);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x500_TrackSensor5(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x500_TrackSensorsA.TrackSensor5 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x500_TrackSensorsA.TrackSensor5 = in;
	return 0;
}

int decode_can_0x500_TrackSensor6(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x500_TrackSensorsA.TrackSensor6);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x500_TrackSensor6(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x500_TrackSensorsA.TrackSensor6 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x500_TrackSensorsA.TrackSensor6 = in;
	return 0;
}

int decode_can_0x500_TrackSensor7(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x500_TrackSensorsA.TrackSensor7);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x500_TrackSensor7(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x500_TrackSensorsA.TrackSensor7 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x500_TrackSensorsA.TrackSensor7 = in;
	return 0;
}

int print_can_0x500_TrackSensorsA(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "TrackSensor0 = (wire: %.0f)\n", (double)(o->can_0x500_TrackSensorsA.TrackSensor0)));
	r = print_helper(r, fprintf(output, "TrackSensor1 = (wire: %.0f)\n", (double)(o->can_0x500_TrackSensorsA.TrackSensor1)));
	r = print_helper(r, fprintf(output, "TrackSensor2 = (wire: %.0f)\n", (double)(o->can_0x500_TrackSensorsA.TrackSensor2)));
	r = print_helper(r, fprintf(output, "TrackSensor3 = (wire: %.0f)\n", (double)(o->can_0x500_TrackSensorsA.TrackSensor3)));
	r = print_helper(r, fprintf(output, "TrackSensor4 = (wire: %.0f)\n", (double)(o->can_0x500_TrackSensorsA.TrackSensor4)));
	r = print_helper(r, fprintf(output, "TrackSensor5 = (wire: %.0f)\n", (double)(o->can_0x500_TrackSensorsA.TrackSensor5)));
	r = print_helper(r, fprintf(output, "TrackSensor6 = (wire: %.0f)\n", (double)(o->can_0x500_TrackSensorsA.TrackSensor6)));
	r = print_helper(r, fprintf(output, "TrackSensor7 = (wire: %.0f)\n", (double)(o->can_0x500_TrackSensorsA.TrackSensor7)));
	return r;
}

static int pack_can_0x501_TrackSensorsB(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* TrackSensor8: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x501_TrackSensorsB.TrackSensor8)) & 0xff;
	i |= x;
	/* TrackSensor9: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x501_TrackSensorsB.TrackSensor9)) & 0xff;
	x <<= 8; 
	i |= x;
	/* TrackSensor10: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x501_TrackSensorsB.TrackSensor10)) & 0xff;
	x <<= 16; 
	i |= x;
	/* TrackSensor11: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x501_TrackSensorsB.TrackSensor11)) & 0xff;
	x <<= 24; 
	i |= x;
	/* TrackSensor12: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x501_TrackSensorsB.TrackSensor12)) & 0xff;
	x <<= 32; 
	i |= x;
	/* TrackSensor13: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x501_TrackSensorsB.TrackSensor13)) & 0xff;
	x <<= 40; 
	i |= x;
	/* TrackSensor14: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x501_TrackSensorsB.TrackSensor14)) & 0xff;
	x <<= 48; 
	i |= x;
	/* TrackSensor15: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x501_TrackSensorsB.TrackSensor15)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x501_TrackSensorsB_tx = 1;
	return 0;
}

static int unpack_can_0x501_TrackSensorsB(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* TrackSensor8: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = i & 0xff;
	o->can_0x501_TrackSensorsB.TrackSensor8 = x;
	/* TrackSensor9: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x501_TrackSensorsB.TrackSensor9 = x;
	/* TrackSensor10: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x501_TrackSensorsB.TrackSensor10 = x;
	/* TrackSensor11: start-bit 24, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x501_TrackSensorsB.TrackSensor11 = x;
	/* TrackSensor12: start-bit 32, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x501_TrackSensorsB.TrackSensor12 = x;
	/* TrackSensor13: start-bit 40, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x501_TrackSensorsB.TrackSensor13 = x;
	/* TrackSensor14: start-bit 48, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x501_TrackSensorsB.TrackSensor14 = x;
	/* TrackSensor15: start-bit 56, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x501_TrackSensorsB.TrackSensor15 = x;
	o->can_0x501_TrackSensorsB_rx = 1;
	o->can_0x501_TrackSensorsB_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x501_TrackSensor8(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x501_TrackSensorsB.TrackSensor8);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x501_TrackSensor8(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x501_TrackSensorsB.TrackSensor8 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x501_TrackSensorsB.TrackSensor8 = in;
	return 0;
}

int decode_can_0x501_TrackSensor9(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x501_TrackSensorsB.TrackSensor9);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x501_TrackSensor9(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x501_TrackSensorsB.TrackSensor9 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x501_TrackSensorsB.TrackSensor9 = in;
	return 0;
}

int decode_can_0x501_TrackSensor10(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x501_TrackSensorsB.TrackSensor10);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x501_TrackSensor10(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x501_TrackSensorsB.TrackSensor10 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x501_TrackSensorsB.TrackSensor10 = in;
	return 0;
}

int decode_can_0x501_TrackSensor11(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x501_TrackSensorsB.TrackSensor11);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x501_TrackSensor11(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x501_TrackSensorsB.TrackSensor11 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x501_TrackSensorsB.TrackSensor11 = in;
	return 0;
}

int decode_can_0x501_TrackSensor12(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x501_TrackSensorsB.TrackSensor12);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x501_TrackSensor12(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x501_TrackSensorsB.TrackSensor12 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x501_TrackSensorsB.TrackSensor12 = in;
	return 0;
}

int decode_can_0x501_TrackSensor13(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x501_TrackSensorsB.TrackSensor13);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x501_TrackSensor13(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x501_TrackSensorsB.TrackSensor13 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x501_TrackSensorsB.TrackSensor13 = in;
	return 0;
}

int decode_can_0x501_TrackSensor14(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x501_TrackSensorsB.TrackSensor14);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x501_TrackSensor14(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x501_TrackSensorsB.TrackSensor14 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x501_TrackSensorsB.TrackSensor14 = in;
	return 0;
}

int decode_can_0x501_TrackSensor15(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x501_TrackSensorsB.TrackSensor15);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x501_TrackSensor15(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x501_TrackSensorsB.TrackSensor15 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x501_TrackSensorsB.TrackSensor15 = in;
	return 0;
}

int print_can_0x501_TrackSensorsB(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "TrackSensor8 = (wire: %.0f)\n", (double)(o->can_0x501_TrackSensorsB.TrackSensor8)));
	r = print_helper(r, fprintf(output, "TrackSensor9 = (wire: %.0f)\n", (double)(o->can_0x501_TrackSensorsB.TrackSensor9)));
	r = print_helper(r, fprintf(output, "TrackSensor10 = (wire: %.0f)\n", (double)(o->can_0x501_TrackSensorsB.TrackSensor10)));
	r = print_helper(r, fprintf(output, "TrackSensor11 = (wire: %.0f)\n", (double)(o->can_0x501_TrackSensorsB.TrackSensor11)));
	r = print_helper(r, fprintf(output, "TrackSensor12 = (wire: %.0f)\n", (double)(o->can_0x501_TrackSensorsB.TrackSensor12)));
	r = print_helper(r, fprintf(output, "TrackSensor13 = (wire: %.0f)\n", (double)(o->can_0x501_TrackSensorsB.TrackSensor13)));
	r = print_helper(r, fprintf(output, "TrackSensor14 = (wire: %.0f)\n", (double)(o->can_0x501_TrackSensorsB.TrackSensor14)));
	r = print_helper(r, fprintf(output, "TrackSensor15 = (wire: %.0f)\n", (double)(o->can_0x501_TrackSensorsB.TrackSensor15)));
	return r;
}

static int pack_can_0x502_TrackSensorsC(can_obj_dbc_funcs_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* TrackSensor16: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x502_TrackSensorsC.TrackSensor16)) & 0xff;
	i |= x;
	/* TrackSensor17: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x502_TrackSensorsC.TrackSensor17)) & 0xff;
	x <<= 8; 
	i |= x;
	/* TrackSensor18: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = ((uint8_t)(o->can_0x502_TrackSensorsC.TrackSensor18)) & 0xff;
	x <<= 16; 
	i |= x;
	*data = (i);
	o->can_0x502_TrackSensorsC_tx = 1;
	return 0;
}

static int unpack_can_0x502_TrackSensorsC(can_obj_dbc_funcs_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* TrackSensor16: start-bit 0, length 8, endianess intel, scaling 0.004, offset 0 */
	x = i & 0xff;
	o->can_0x502_TrackSensorsC.TrackSensor16 = x;
	/* TrackSensor17: start-bit 8, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x502_TrackSensorsC.TrackSensor17 = x;
	/* TrackSensor18: start-bit 16, length 8, endianess intel, scaling 0.004, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x502_TrackSensorsC.TrackSensor18 = x;
	o->can_0x502_TrackSensorsC_rx = 1;
	o->can_0x502_TrackSensorsC_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x502_TrackSensor16(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x502_TrackSensorsC.TrackSensor16);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x502_TrackSensor16(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x502_TrackSensorsC.TrackSensor16 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x502_TrackSensorsC.TrackSensor16 = in;
	return 0;
}

int decode_can_0x502_TrackSensor17(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x502_TrackSensorsC.TrackSensor17);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x502_TrackSensor17(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x502_TrackSensorsC.TrackSensor17 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x502_TrackSensorsC.TrackSensor17 = in;
	return 0;
}

int decode_can_0x502_TrackSensor18(const can_obj_dbc_funcs_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x502_TrackSensorsC.TrackSensor18);
	rval *= 0.004;
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x502_TrackSensor18(can_obj_dbc_funcs_h_t *o, double in) {
	assert(o);
	o->can_0x502_TrackSensorsC.TrackSensor18 = 0;
	if (in > 1)
		return -1;
	in *= 250;
	o->can_0x502_TrackSensorsC.TrackSensor18 = in;
	return 0;
}

int print_can_0x502_TrackSensorsC(const can_obj_dbc_funcs_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "TrackSensor16 = (wire: %.0f)\n", (double)(o->can_0x502_TrackSensorsC.TrackSensor16)));
	r = print_helper(r, fprintf(output, "TrackSensor17 = (wire: %.0f)\n", (double)(o->can_0x502_TrackSensorsC.TrackSensor17)));
	r = print_helper(r, fprintf(output, "TrackSensor18 = (wire: %.0f)\n", (double)(o->can_0x502_TrackSensorsC.TrackSensor18)));
	return r;
}

int unpack_message(can_obj_dbc_funcs_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x080: return unpack_can_0x080_PlayerControls(o, data, dlc, time_stamp);
	case 0x300: return unpack_can_0x300_ObstacleSensorsA(o, data, dlc, time_stamp);
	case 0x301: return unpack_can_0x301_ObstacleSensorsB(o, data, dlc, time_stamp);
	case 0x302: return unpack_can_0x302_ObstacleSensorsC(o, data, dlc, time_stamp);
	case 0x303: return unpack_can_0x303_ObstacleSensorsD(o, data, dlc, time_stamp);
	case 0x304: return unpack_can_0x304_ObstacleSensorsE(o, data, dlc, time_stamp);
	case 0x400: return unpack_can_0x400_FuelGearEngine(o, data, dlc, time_stamp);
	case 0x401: return unpack_can_0x401_CarDamage(o, data, dlc, time_stamp);
	case 0x402: return unpack_can_0x402_WheelSpinVelocity(o, data, dlc, time_stamp);
	case 0x403: return unpack_can_0x403_Speed(o, data, dlc, time_stamp);
	case 0x404: return unpack_can_0x404_Position(o, data, dlc, time_stamp);
	case 0x405: return unpack_can_0x405_AngleAndOffset(o, data, dlc, time_stamp);
	case 0x406: return unpack_can_0x406_LapTime(o, data, dlc, time_stamp);
	case 0x407: return unpack_can_0x407_DistanceRaced(o, data, dlc, time_stamp);
	case 0x500: return unpack_can_0x500_TrackSensorsA(o, data, dlc, time_stamp);
	case 0x501: return unpack_can_0x501_TrackSensorsB(o, data, dlc, time_stamp);
	case 0x502: return unpack_can_0x502_TrackSensorsC(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_dbc_funcs_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x080: return pack_can_0x080_PlayerControls(o, data);
	case 0x300: return pack_can_0x300_ObstacleSensorsA(o, data);
	case 0x301: return pack_can_0x301_ObstacleSensorsB(o, data);
	case 0x302: return pack_can_0x302_ObstacleSensorsC(o, data);
	case 0x303: return pack_can_0x303_ObstacleSensorsD(o, data);
	case 0x304: return pack_can_0x304_ObstacleSensorsE(o, data);
	case 0x400: return pack_can_0x400_FuelGearEngine(o, data);
	case 0x401: return pack_can_0x401_CarDamage(o, data);
	case 0x402: return pack_can_0x402_WheelSpinVelocity(o, data);
	case 0x403: return pack_can_0x403_Speed(o, data);
	case 0x404: return pack_can_0x404_Position(o, data);
	case 0x405: return pack_can_0x405_AngleAndOffset(o, data);
	case 0x406: return pack_can_0x406_LapTime(o, data);
	case 0x407: return pack_can_0x407_DistanceRaced(o, data);
	case 0x500: return pack_can_0x500_TrackSensorsA(o, data);
	case 0x501: return pack_can_0x501_TrackSensorsB(o, data);
	case 0x502: return pack_can_0x502_TrackSensorsC(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_dbc_funcs_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x080: return print_can_0x080_PlayerControls(o, output);
	case 0x300: return print_can_0x300_ObstacleSensorsA(o, output);
	case 0x301: return print_can_0x301_ObstacleSensorsB(o, output);
	case 0x302: return print_can_0x302_ObstacleSensorsC(o, output);
	case 0x303: return print_can_0x303_ObstacleSensorsD(o, output);
	case 0x304: return print_can_0x304_ObstacleSensorsE(o, output);
	case 0x400: return print_can_0x400_FuelGearEngine(o, output);
	case 0x401: return print_can_0x401_CarDamage(o, output);
	case 0x402: return print_can_0x402_WheelSpinVelocity(o, output);
	case 0x403: return print_can_0x403_Speed(o, output);
	case 0x404: return print_can_0x404_Position(o, output);
	case 0x405: return print_can_0x405_AngleAndOffset(o, output);
	case 0x406: return print_can_0x406_LapTime(o, output);
	case 0x407: return print_can_0x407_DistanceRaced(o, output);
	case 0x500: return print_can_0x500_TrackSensorsA(o, output);
	case 0x501: return print_can_0x501_TrackSensorsB(o, output);
	case 0x502: return print_can_0x502_TrackSensorsC(o, output);
	default: break; 
	}
	return -1; 
}

