/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef DBC_FUNCS_H
#define DBC_FUNCS_H

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

typedef PREPACK struct {
	uint8_t Steer; /* scaling 0.0, offset -1.0, units m  */
	uint8_t Accel; /* scaling 0.0, offset 0.0, units m  */
	uint8_t Brake; /* scaling 0.0, offset 0.0, units m  */
	uint8_t Gear; /* scaling 1.0, offset 0.0, units m  */
	uint8_t Clutch; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x080_PlayerControls_t;

typedef PREPACK struct {
	uint8_t ObstacleSensor0; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor1; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor2; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor3; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor4; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor5; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor6; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor7; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x300_ObstacleSensorsA_t;

typedef PREPACK struct {
	uint8_t ObstacleSensor8; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor9; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor10; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor11; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor12; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor13; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor14; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor15; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x301_ObstacleSensorsB_t;

typedef PREPACK struct {
	uint8_t ObstacleSensor16; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor17; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor18; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor19; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor20; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor21; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor22; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor23; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x302_ObstacleSensorsC_t;

typedef PREPACK struct {
	uint8_t ObstacleSensor24; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor25; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor26; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor27; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor28; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor29; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor30; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor31; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x303_ObstacleSensorsD_t;

typedef PREPACK struct {
	uint8_t ObstacleSensor32; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor33; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor34; /* scaling 0.0, offset 0.0, units m  */
	uint8_t ObstacleSensor35; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x304_ObstacleSensorsE_t;

typedef PREPACK struct {
	uint32_t FuelLevel; /* scaling 0.0, offset 0.0, units l  */
	uint32_t EngineSpeed; /* scaling 0.0, offset 0.0, units RPM  */
	uint8_t Gear; /* scaling 1.0, offset -1.0, units (unit)  */
} POSTPACK can_0x400_FuelGearEngine_t;

typedef PREPACK struct {
	uint32_t Damage; /* scaling 1.0, offset 0.0, units (unit)  */
} POSTPACK can_0x401_CarDamage_t;

typedef PREPACK struct {
	uint16_t WheelSpin0; /* scaling 1.0, offset -20000.0, units RPM  */
	uint16_t WheelSpin1; /* scaling 1.0, offset -20000.0, units RPM  */
	uint16_t WheelSpin2; /* scaling 1.0, offset -20000.0, units RPM  */
	uint16_t WheelSpin3; /* scaling 1.0, offset -20000.0, units RPM  */
} POSTPACK can_0x402_WheelSpinVelocity_t;

typedef PREPACK struct {
	uint32_t SpeedX; /* scaling 0.0, offset -1000.0, units m/s  */
	uint32_t SpeedY; /* scaling 0.0, offset -1000.0, units m/s  */
	uint32_t SpeedZ; /* scaling 0.0, offset -1000.0, units m/s  */
} POSTPACK can_0x403_Speed_t;

typedef PREPACK struct {
	uint32_t Position; /* scaling 1.0, offset 0.0, units (unit)  */
	float PositionZ; /* scaling 1.0, offset 0.0, units m , floating */
} POSTPACK can_0x404_Position_t;

typedef PREPACK struct {
	uint16_t Angle; /* scaling 0.0, offset 0.0, units rad  */
	uint16_t DistanceFromMiddle; /* scaling 0.0, offset -1.0, units (unit)  */
} POSTPACK can_0x405_AngleAndOffset_t;

typedef PREPACK struct {
	float CurrentLapTime; /* scaling 1.0, offset 0.0, units s , floating */
	float LastLapTime; /* scaling 1.0, offset 0.0, units s , floating */
} POSTPACK can_0x406_LapTime_t;

typedef PREPACK struct {
	float DistanceFromStartLine; /* scaling 1.0, offset 0.0, units m , floating */
	float CurrentDistanceRaced; /* scaling 1.0, offset 0.0, units m , floating */
} POSTPACK can_0x407_DistanceRaced_t;

typedef PREPACK struct {
	uint8_t TrackSensor0; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor1; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor2; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor3; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor4; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor5; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor6; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor7; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x500_TrackSensorsA_t;

typedef PREPACK struct {
	uint8_t TrackSensor8; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor9; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor10; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor11; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor12; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor13; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor14; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor15; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x501_TrackSensorsB_t;

typedef PREPACK struct {
	uint8_t TrackSensor16; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor17; /* scaling 0.0, offset 0.0, units m  */
	uint8_t TrackSensor18; /* scaling 0.0, offset 0.0, units m  */
} POSTPACK can_0x502_TrackSensorsC_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x080_PlayerControls_time_stamp_rx;
	dbcc_time_stamp_t can_0x300_ObstacleSensorsA_time_stamp_rx;
	dbcc_time_stamp_t can_0x301_ObstacleSensorsB_time_stamp_rx;
	dbcc_time_stamp_t can_0x302_ObstacleSensorsC_time_stamp_rx;
	dbcc_time_stamp_t can_0x303_ObstacleSensorsD_time_stamp_rx;
	dbcc_time_stamp_t can_0x304_ObstacleSensorsE_time_stamp_rx;
	dbcc_time_stamp_t can_0x400_FuelGearEngine_time_stamp_rx;
	dbcc_time_stamp_t can_0x401_CarDamage_time_stamp_rx;
	dbcc_time_stamp_t can_0x402_WheelSpinVelocity_time_stamp_rx;
	dbcc_time_stamp_t can_0x403_Speed_time_stamp_rx;
	dbcc_time_stamp_t can_0x404_Position_time_stamp_rx;
	dbcc_time_stamp_t can_0x405_AngleAndOffset_time_stamp_rx;
	dbcc_time_stamp_t can_0x406_LapTime_time_stamp_rx;
	dbcc_time_stamp_t can_0x407_DistanceRaced_time_stamp_rx;
	dbcc_time_stamp_t can_0x500_TrackSensorsA_time_stamp_rx;
	dbcc_time_stamp_t can_0x501_TrackSensorsB_time_stamp_rx;
	dbcc_time_stamp_t can_0x502_TrackSensorsC_time_stamp_rx;
	unsigned can_0x080_PlayerControls_status : 2;
	unsigned can_0x080_PlayerControls_tx : 1;
	unsigned can_0x080_PlayerControls_rx : 1;
	unsigned can_0x300_ObstacleSensorsA_status : 2;
	unsigned can_0x300_ObstacleSensorsA_tx : 1;
	unsigned can_0x300_ObstacleSensorsA_rx : 1;
	unsigned can_0x301_ObstacleSensorsB_status : 2;
	unsigned can_0x301_ObstacleSensorsB_tx : 1;
	unsigned can_0x301_ObstacleSensorsB_rx : 1;
	unsigned can_0x302_ObstacleSensorsC_status : 2;
	unsigned can_0x302_ObstacleSensorsC_tx : 1;
	unsigned can_0x302_ObstacleSensorsC_rx : 1;
	unsigned can_0x303_ObstacleSensorsD_status : 2;
	unsigned can_0x303_ObstacleSensorsD_tx : 1;
	unsigned can_0x303_ObstacleSensorsD_rx : 1;
	unsigned can_0x304_ObstacleSensorsE_status : 2;
	unsigned can_0x304_ObstacleSensorsE_tx : 1;
	unsigned can_0x304_ObstacleSensorsE_rx : 1;
	unsigned can_0x400_FuelGearEngine_status : 2;
	unsigned can_0x400_FuelGearEngine_tx : 1;
	unsigned can_0x400_FuelGearEngine_rx : 1;
	unsigned can_0x401_CarDamage_status : 2;
	unsigned can_0x401_CarDamage_tx : 1;
	unsigned can_0x401_CarDamage_rx : 1;
	unsigned can_0x402_WheelSpinVelocity_status : 2;
	unsigned can_0x402_WheelSpinVelocity_tx : 1;
	unsigned can_0x402_WheelSpinVelocity_rx : 1;
	unsigned can_0x403_Speed_status : 2;
	unsigned can_0x403_Speed_tx : 1;
	unsigned can_0x403_Speed_rx : 1;
	unsigned can_0x404_Position_status : 2;
	unsigned can_0x404_Position_tx : 1;
	unsigned can_0x404_Position_rx : 1;
	unsigned can_0x405_AngleAndOffset_status : 2;
	unsigned can_0x405_AngleAndOffset_tx : 1;
	unsigned can_0x405_AngleAndOffset_rx : 1;
	unsigned can_0x406_LapTime_status : 2;
	unsigned can_0x406_LapTime_tx : 1;
	unsigned can_0x406_LapTime_rx : 1;
	unsigned can_0x407_DistanceRaced_status : 2;
	unsigned can_0x407_DistanceRaced_tx : 1;
	unsigned can_0x407_DistanceRaced_rx : 1;
	unsigned can_0x500_TrackSensorsA_status : 2;
	unsigned can_0x500_TrackSensorsA_tx : 1;
	unsigned can_0x500_TrackSensorsA_rx : 1;
	unsigned can_0x501_TrackSensorsB_status : 2;
	unsigned can_0x501_TrackSensorsB_tx : 1;
	unsigned can_0x501_TrackSensorsB_rx : 1;
	unsigned can_0x502_TrackSensorsC_status : 2;
	unsigned can_0x502_TrackSensorsC_tx : 1;
	unsigned can_0x502_TrackSensorsC_rx : 1;
	can_0x080_PlayerControls_t can_0x080_PlayerControls;
	can_0x300_ObstacleSensorsA_t can_0x300_ObstacleSensorsA;
	can_0x301_ObstacleSensorsB_t can_0x301_ObstacleSensorsB;
	can_0x302_ObstacleSensorsC_t can_0x302_ObstacleSensorsC;
	can_0x303_ObstacleSensorsD_t can_0x303_ObstacleSensorsD;
	can_0x304_ObstacleSensorsE_t can_0x304_ObstacleSensorsE;
	can_0x400_FuelGearEngine_t can_0x400_FuelGearEngine;
	can_0x401_CarDamage_t can_0x401_CarDamage;
	can_0x402_WheelSpinVelocity_t can_0x402_WheelSpinVelocity;
	can_0x403_Speed_t can_0x403_Speed;
	can_0x404_Position_t can_0x404_Position;
	can_0x405_AngleAndOffset_t can_0x405_AngleAndOffset;
	can_0x406_LapTime_t can_0x406_LapTime;
	can_0x407_DistanceRaced_t can_0x407_DistanceRaced;
	can_0x500_TrackSensorsA_t can_0x500_TrackSensorsA;
	can_0x501_TrackSensorsB_t can_0x501_TrackSensorsB;
	can_0x502_TrackSensorsC_t can_0x502_TrackSensorsC;
} POSTPACK can_obj_dbc_funcs_h_t;

int unpack_message(can_obj_dbc_funcs_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message(can_obj_dbc_funcs_h_t *o, const unsigned long id, uint64_t *data);
int print_message(const can_obj_dbc_funcs_h_t *o, const unsigned long id, FILE *output);

int decode_can_0x080_Steer(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x080_Steer(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x080_Accel(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x080_Accel(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x080_Brake(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x080_Brake(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x080_Gear(const can_obj_dbc_funcs_h_t *o, uint8_t *out);
int encode_can_0x080_Gear(can_obj_dbc_funcs_h_t *o, uint8_t in);
int decode_can_0x080_Clutch(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x080_Clutch(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x300_ObstacleSensor0(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x300_ObstacleSensor0(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x300_ObstacleSensor1(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x300_ObstacleSensor1(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x300_ObstacleSensor2(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x300_ObstacleSensor2(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x300_ObstacleSensor3(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x300_ObstacleSensor3(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x300_ObstacleSensor4(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x300_ObstacleSensor4(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x300_ObstacleSensor5(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x300_ObstacleSensor5(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x300_ObstacleSensor6(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x300_ObstacleSensor6(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x300_ObstacleSensor7(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x300_ObstacleSensor7(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x301_ObstacleSensor8(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x301_ObstacleSensor8(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x301_ObstacleSensor9(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x301_ObstacleSensor9(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x301_ObstacleSensor10(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x301_ObstacleSensor10(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x301_ObstacleSensor11(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x301_ObstacleSensor11(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x301_ObstacleSensor12(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x301_ObstacleSensor12(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x301_ObstacleSensor13(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x301_ObstacleSensor13(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x301_ObstacleSensor14(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x301_ObstacleSensor14(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x301_ObstacleSensor15(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x301_ObstacleSensor15(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x302_ObstacleSensor16(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x302_ObstacleSensor16(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x302_ObstacleSensor17(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x302_ObstacleSensor17(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x302_ObstacleSensor18(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x302_ObstacleSensor18(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x302_ObstacleSensor19(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x302_ObstacleSensor19(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x302_ObstacleSensor20(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x302_ObstacleSensor20(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x302_ObstacleSensor21(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x302_ObstacleSensor21(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x302_ObstacleSensor22(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x302_ObstacleSensor22(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x302_ObstacleSensor23(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x302_ObstacleSensor23(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x303_ObstacleSensor24(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x303_ObstacleSensor24(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x303_ObstacleSensor25(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x303_ObstacleSensor25(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x303_ObstacleSensor26(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x303_ObstacleSensor26(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x303_ObstacleSensor27(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x303_ObstacleSensor27(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x303_ObstacleSensor28(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x303_ObstacleSensor28(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x303_ObstacleSensor29(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x303_ObstacleSensor29(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x303_ObstacleSensor30(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x303_ObstacleSensor30(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x303_ObstacleSensor31(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x303_ObstacleSensor31(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x304_ObstacleSensor32(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x304_ObstacleSensor32(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x304_ObstacleSensor33(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x304_ObstacleSensor33(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x304_ObstacleSensor34(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x304_ObstacleSensor34(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x304_ObstacleSensor35(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x304_ObstacleSensor35(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x400_FuelLevel(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x400_FuelLevel(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x400_EngineSpeed(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x400_EngineSpeed(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x400_Gear(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x400_Gear(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x401_Damage(const can_obj_dbc_funcs_h_t *o, uint32_t *out);
int encode_can_0x401_Damage(can_obj_dbc_funcs_h_t *o, uint32_t in);


int decode_can_0x402_WheelSpin0(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x402_WheelSpin0(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x402_WheelSpin1(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x402_WheelSpin1(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x402_WheelSpin2(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x402_WheelSpin2(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x402_WheelSpin3(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x402_WheelSpin3(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x403_SpeedX(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x403_SpeedX(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x403_SpeedY(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x403_SpeedY(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x403_SpeedZ(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x403_SpeedZ(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x404_Position(const can_obj_dbc_funcs_h_t *o, uint32_t *out);
int encode_can_0x404_Position(can_obj_dbc_funcs_h_t *o, uint32_t in);
int decode_can_0x404_PositionZ(const can_obj_dbc_funcs_h_t *o, float *out);
int encode_can_0x404_PositionZ(can_obj_dbc_funcs_h_t *o, float in);


int decode_can_0x405_Angle(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x405_Angle(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x405_DistanceFromMiddle(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x405_DistanceFromMiddle(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x406_CurrentLapTime(const can_obj_dbc_funcs_h_t *o, float *out);
int encode_can_0x406_CurrentLapTime(can_obj_dbc_funcs_h_t *o, float in);
int decode_can_0x406_LastLapTime(const can_obj_dbc_funcs_h_t *o, float *out);
int encode_can_0x406_LastLapTime(can_obj_dbc_funcs_h_t *o, float in);


int decode_can_0x407_DistanceFromStartLine(const can_obj_dbc_funcs_h_t *o, float *out);
int encode_can_0x407_DistanceFromStartLine(can_obj_dbc_funcs_h_t *o, float in);
int decode_can_0x407_CurrentDistanceRaced(const can_obj_dbc_funcs_h_t *o, float *out);
int encode_can_0x407_CurrentDistanceRaced(can_obj_dbc_funcs_h_t *o, float in);


int decode_can_0x500_TrackSensor0(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x500_TrackSensor0(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x500_TrackSensor1(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x500_TrackSensor1(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x500_TrackSensor2(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x500_TrackSensor2(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x500_TrackSensor3(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x500_TrackSensor3(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x500_TrackSensor4(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x500_TrackSensor4(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x500_TrackSensor5(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x500_TrackSensor5(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x500_TrackSensor6(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x500_TrackSensor6(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x500_TrackSensor7(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x500_TrackSensor7(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x501_TrackSensor8(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x501_TrackSensor8(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x501_TrackSensor9(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x501_TrackSensor9(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x501_TrackSensor10(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x501_TrackSensor10(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x501_TrackSensor11(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x501_TrackSensor11(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x501_TrackSensor12(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x501_TrackSensor12(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x501_TrackSensor13(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x501_TrackSensor13(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x501_TrackSensor14(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x501_TrackSensor14(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x501_TrackSensor15(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x501_TrackSensor15(can_obj_dbc_funcs_h_t *o, double in);


int decode_can_0x502_TrackSensor16(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x502_TrackSensor16(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x502_TrackSensor17(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x502_TrackSensor17(can_obj_dbc_funcs_h_t *o, double in);
int decode_can_0x502_TrackSensor18(const can_obj_dbc_funcs_h_t *o, double *out);
int encode_can_0x502_TrackSensor18(can_obj_dbc_funcs_h_t *o, double in);


#ifdef __cplusplus
} 
#endif

#endif
